### ISSUE TITLE
Why do we need this repository?

### ISSUE THREAD

**Issue by brenton** [openshift/openshift-base#3]
I'm curious why this repository's content couldn't live under https://github.com/openshift/origin/tree/master/images/base.

**Comment by bparees** [comment]
This stuff isn't really origin related, it's the base for STI builder images.  so it's a different base.  the name might not be ideal.

**Comment by brenton** [comment]
Any reason it couldn't be in the sti repository?

**Comment by bparees** [comment]
strictly speaking, probably not, but there's also no requirement that STI images build on top of this image, so it's a loose coupling at best.

@mfojtik @jhadvig what do you think?

**Comment by mfojtik** [comment]
@bparees this might also be base for database image right? so that might be a reason why not to put it into STI repository.

also why not calling this image "openshift/base" ;-)

**Comment by bparees** [comment]
@mfojtik i dunno, who created it? :)

**Comment by mfojtik** [comment]
@bparees @jhadvig created it. I fixed the naming here: https://github.com/openshift/openshift-base/pull/4

@brenton we do need to setup trusted Docker hub builds for this repo and for the centos-7 image.

**Comment by bparees** [comment]
@mfojtik yes we do...  i can do that.

**Comment by bparees** [comment]
the github repo itself should be renamed to "sti-base" imho.

the docker image can be openshift/base-centos7 i guess, since that matches our other STI related images (no STI in the name)

**Comment by mfojtik** [comment]
+1

**Comment by brenton** [comment]
Thanks, this answers my questions.  I'd love to see a more useful github repo name but I know how naming things goes.  It's always going to confuse someone. :)

**Comment by bparees** [comment]
@brenton it's been renamed.
